doshibu_aw_home:
    path :   /
    defaults:
        _controller: DoshibuAfkWatchBundle:Movie:index

doshibu_aw_single:
    path :   /single/{id}
    defaults: 
        _controller : DoshibuAfkWatchBundle:Movie:single
        id: 1
    requirements:
        id: \d+

doshibu_aw_genre:
    path :   /genre/{slug}
    defaults: 
        _controller : DoshibuAfkWatchBundle:Movie:genre
        slug: action

doshibu_aw_series:
    path :   /series
    defaults:
        _controller : DoshibuAfkWatchBundle:Movie:series

doshibu_aw_news:
    path :   /news
    defaults:
        _controller : DoshibuAfkWatchBundle:Movie:news
    requirements:
        id: \d+

doshibu_aw_news_single:
    path :   /news-single/{id}
    defaults: 
        _controller : DoshibuAfkWatchBundle:Movie:newsSingle
        id: 1
    requirements:
        id: \d+

doshibu_aw_pays:
    path :   /pays/{slug}
    defaults:
        _controller : DoshibuAfkWatchBundle:Movie:pays
        slug: france

doshibu_aw_list:
    path :   /list
    defaults:
        _controller : DoshibuAfkWatchBundle:Movie:list
    requirements:
        id: \d+

doshibu_aw_faq:
    path :   /faq
    defaults:
        _controller : DoshibuAfkWatchBundle:Movie:faq

doshibu_aw_contact:
    path :   /contact
    defaults:
        _controller : DoshibuAfkWatchBundle:Movie:contact