doshibu_aw_home:
    path :   /
    defaults:
        _controller: DoshibuAfkWatchBundle:Platform:index

doshibu_aw_movie:
    path :   /movie/{slug}
    defaults: 
        _controller : DoshibuAfkWatchBundle:Movie:movie

doshibu_aw_genre:
    path :   /genre/{slug}/{page}
    defaults: 
        _controller : DoshibuAfkWatchBundle:Gender:genre
        slug: action
        page: 1
    requirements:
        page: \d+

doshibu_aw_pays:
    path :   /pays/{slug}/{page}
    defaults:
        _controller : DoshibuAfkWatchBundle:Country:pays
        slug: france
        page: 1
    requirements:
        page: \d+

doshibu_aw_series:
    path :   /series
    defaults:
        _controller : DoshibuAfkWatchBundle:Serie:series
        
doshibu_aw_serie:
    path :   /serie/{slug}
    defaults: 
        _controller : DoshibuAfkWatchBundle:Serie:serie

doshibu_aw_news:
    path :   /news/{media}/{page}
    defaults:
        _controller : DoshibuAfkWatchBundle:News:news
        page: 1
    requirements:
        page: \d+

doshibu_aw_news_single:
    path :   /news-single/{media}/{slug}
    defaults: 
        _controller : DoshibuAfkWatchBundle:News:newsSingle

doshibu_aw_list:
    path :   /list/{prefix}/{page}
    defaults:
        _controller : DoshibuAfkWatchBundle:Platform:list
        prefix: int
        page: 1
    requirements:
        page: \d+

doshibu_aw_faq:
    path :   /faq
    defaults:
        _controller : DoshibuAfkWatchBundle:Platform:faq

doshibu_aw_contact:
    path :   /contact
    defaults:
        _controller : DoshibuAfkWatchBundle:Platform:contact