<?php

namespace Doshibu\AfkWatchBundle\Repository;

/**
 * MovieGenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieGenreRepository extends \Doctrine\ORM\EntityRepository
{
}
