<?php

namespace Doshibu\AfkWatchBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
	public function findAllAsArray()
	{
		return $this
			->createQueryBuilder('a')
			->getQuery()
			->getResult(Query::HYDRATE_ARRAY);
	}
}
