<?php

namespace Doshibu\AfkWatchBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function findMovieRecentsPage($page, $nbPerPage, $asArray=false)
	{
		$qb = $this->createQueryBuilder('s')
			->join('s.movie', 'movie')
			->addSelect('movie')
			->leftJoin('movie.imageSmall', 'imgS')
			->addSelect('imgS')
			->leftJoin('movie.imageLarge', 'imgL')
			->addSelect('imgL')
			->orderBy('s.addedAt', 'DESC')
			->getQuery();

		$qb->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage);

		if($asArray === true)
		{
			$qb->setHydrationMode(Query::HYDRATE_ARRAY);
		}

		return new Paginator($qb, $fetchJoinCollection=true);
	}

	public function findMostViewed($limit=10, $asArray=false)
	{
		$qb = $this->createQueryBuilder('s')
			->orderBy('s.nbViews', 'DESC')
			->getQuery()
			->setMaxResults($limit);

		return ($asArray) ? $qb->getResult(Query::HYDRATE_ARRAY) : $qb->getResult();
	}

	public function findMostRecent($limit=10, $asArray=false)
	{
		$qb = $this->createQueryBuilder('s')
			->orderBy('s.addedAt', 'DESC')
			->getQuery()
			->setMaxResults($limit);

		return ($asArray) ? $qb->getResult(Query::HYDRATE_ARRAY) : $qb->getResult();
	}

	public function findSerieRecentsPage($page, $nbPerPage, $asArray=false)
	{
		$qb = $this->createQueryBuilder('s')
			->join('s.serie', 'serie')
			->addSelect('serie')
			->leftJoin('serie.imageSmall', 'imgS')
			->addSelect('imgS')
			->leftJoin('serie.imageLarge', 'imgL')
			->addSelect('imgL')
			->orderBy('s.addedAt', 'DESC')
			->getQuery();

		$qb->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage);

		if($asArray === true)
		{
			$qb->setHydrationMode(Query::HYDRATE_ARRAY);
		}

		return new Paginator($qb, $fetchJoinCollection=true);
	}
}
