<?php

namespace Doshibu\AfkWatchBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
	public function getAll($asArray=false)
	{
		$qb = $this
			->createQueryBuilder('p')
			->getQuery();

		return $asArray ? $qb->getResult(Query::HYDRATE_ARRAY) : $qb->getResult();
	}
}
